import { Product } from "@/types/product";

import laptopMacbook from "@/assets/laptop-macbook.jpg";
import laptopDell from "@/assets/laptop-dell.jpg";
import laptopGaming from "@/assets/laptop-gaming.jpg";
import phoneIphone from "@/assets/phone-iphone.jpg";
import phoneSamsung from "@/assets/phone-samsung.jpg";
import cameraDslr from "@/assets/camera-dslr.jpg";
import speakerWireless from "@/assets/speaker-wireless.jpg";
import smartwatchApple from "@/assets/smartwatch-apple.jpg";
import tvSmart from "@/assets/tv-smart.jpg";
import acModern from "@/assets/ac-modern.jpg";
import product1 from "@/assets/product-1.jpg";
import product2 from "@/assets/product-2.jpg";

export const products: Product[] = [
  // Laptops
  {
    id: "1",
    name: "MacBook Pro 16-inch",
    price: 199920,
    description: "Powerful M3 Pro chip, stunning Retina display. Perfect for professionals.",
    image: laptopMacbook,
    category: "Laptops",
    rating: 4.9,
    reviews: 876,
    inStock: true,
    discount: 10,
  },
  {
    id: "2",
    name: "Dell XPS 15",
    price: 1899.99,
    description: "Intel Core i7, 16GB RAM. Sleek design, powerful performance.",
    image: laptopDell,
    category: "Laptops",
    rating: 4.7,
    reviews: 542,
    inStock: true,
  },
  {
    id: "3",
    name: "HP Pavilion Gaming",
    price: 1299.99,
    description: "NVIDIA RTX graphics, 144Hz display. Gaming powerhouse.",
    image: laptopGaming,
    category: "Laptops",
    rating: 4.6,
    reviews: 412,
    inStock: true,
    discount: 15,
  },
  {
    id: "4",
    name: "Lenovo ThinkPad X1",
    price: 1799.99,
    description: "Business-grade security, durable build. Professional's choice.",
    image: laptopDell,
    category: "Laptops",
    rating: 4.8,
    reviews: 328,
    inStock: true,
  },
  {
    id: "5",
    name: "ASUS ROG Zephyrus",
    price: 2199.99,
    description: "AMD Ryzen 9, liquid cooling. Elite gaming laptop.",
    image: laptopGaming,
    category: "Laptops",
    rating: 4.9,
    reviews: 654,
    inStock: false,
  },
  {
    id: "6",
    name: "Acer Swift 3",
    price: 899.99,
    description: "Lightweight aluminum body, all-day battery. Perfect for travel.",
    image: laptopMacbook,
    category: "Laptops",
    rating: 4.5,
    reviews: 287,
    inStock: true,
    discount: 20,
  },

  // Mobiles
  {
    id: "7",
    name: "iPhone 15 Pro Max",
    price: 1199.99,
    description: "A17 Pro chip, titanium design. Professional camera system.",
    image: phoneIphone,
    category: "Mobiles",
    rating: 4.9,
    reviews: 1205,
    inStock: true,
  },
  {
    id: "8",
    name: "Samsung Galaxy S24 Ultra",
    price: 1099.99,
    description: "200MP camera, S Pen included. Ultimate Android flagship.",
    image: phoneSamsung,
    category: "Mobiles",
    rating: 4.8,
    reviews: 987,
    inStock: true,
    discount: 12,
  },
  {
    id: "9",
    name: "Google Pixel 8 Pro",
    price: 899.99,
    description: "AI-powered photography, clean Android. Pure Google experience.",
    image: phoneIphone,
    category: "Mobiles",
    rating: 4.7,
    reviews: 743,
    inStock: true,
  },
  {
    id: "10",
    name: "OnePlus 12",
    price: 799.99,
    description: "Snapdragon 8 Gen 3, 120Hz display. Flagship killer returns.",
    image: phoneSamsung,
    category: "Mobiles",
    rating: 4.6,
    reviews: 542,
    inStock: true,
    discount: 25,
  },
  {
    id: "11",
    name: "Xiaomi 14 Pro",
    price: 749.99,
    description: "Leica optics, fast charging. Premium at affordable price.",
    image: phoneIphone,
    category: "Mobiles",
    rating: 4.5,
    reviews: 421,
    inStock: true,
  },
  {
    id: "12",
    name: "Nothing Phone 2",
    price: 599.99,
    description: "Unique Glyph interface, clean design. Stand out from crowd.",
    image: phoneSamsung,
    category: "Mobiles",
    rating: 4.4,
    reviews: 312,
    inStock: false,
  },

  // Cameras
  {
    id: "13",
    name: "Canon EOS R5",
    price: 3899.99,
    description: "45MP sensor, 8K video. Professional mirrorless camera.",
    image: cameraDslr,
    category: "Cameras",
    rating: 4.9,
    reviews: 456,
    inStock: true,
  },
  {
    id: "14",
    name: "Sony A7 IV",
    price: 2499.99,
    description: "33MP full-frame, excellent autofocus. Hybrid shooting beast.",
    image: cameraDslr,
    category: "Cameras",
    rating: 4.8,
    reviews: 623,
    inStock: true,
    discount: 15,
  },
  {
    id: "15",
    name: "Nikon Z8",
    price: 3699.99,
    description: "45.7MP stacked sensor, 8K 60fps. Video powerhouse.",
    image: cameraDslr,
    category: "Cameras",
    rating: 4.8,
    reviews: 387,
    inStock: true,
  },
  {
    id: "16",
    name: "Fujifilm X-T5",
    price: 1699.99,
    description: "40MP APS-C, film simulations. Retro design meets modern tech.",
    image: cameraDslr,
    category: "Cameras",
    rating: 4.7,
    reviews: 512,
    inStock: true,
  },
  {
    id: "17",
    name: "Panasonic Lumix S5 II",
    price: 1999.99,
    description: "24MP full-frame, phase detect AF. Affordable excellence.",
    image: cameraDslr,
    category: "Cameras",
    rating: 4.6,
    reviews: 289,
    inStock: true,
    discount: 20,
  },
  {
    id: "18",
    name: "GoPro Hero 12",
    price: 399.99,
    description: "5.3K video, waterproof. Action camera champion.",
    image: cameraDslr,
    category: "Cameras",
    rating: 4.7,
    reviews: 834,
    inStock: true,
  },

  // Speakers
  {
    id: "19",
    name: "Sonos Era 300",
    price: 449.99,
    description: "Spatial audio, Dolby Atmos. Revolutionary smart speaker.",
    image: speakerWireless,
    category: "Speakers",
    rating: 4.8,
    reviews: 412,
    inStock: true,
  },
  {
    id: "20",
    name: "JBL Charge 5",
    price: 179.99,
    description: "20 hours battery, IP67 waterproof. Party anywhere.",
    image: speakerWireless,
    category: "Speakers",
    rating: 4.7,
    reviews: 876,
    inStock: true,
    discount: 18,
  },
  {
    id: "21",
    name: "Bose SoundLink Revolve+",
    price: 329.99,
    description: "360-degree sound, premium build. Portable perfection.",
    image: speakerWireless,
    category: "Speakers",
    rating: 4.6,
    reviews: 543,
    inStock: true,
  },
  {
    id: "22",
    name: "Marshall Emberton II",
    price: 169.99,
    description: "Iconic design, punchy bass. Rock-inspired audio.",
    image: speakerWireless,
    category: "Speakers",
    rating: 4.5,
    reviews: 387,
    inStock: true,
  },
  {
    id: "23",
    name: "Ultimate Ears Boom 3",
    price: 149.99,
    description: "Rugged, waterproof, loud. Festival-ready speaker.",
    image: speakerWireless,
    category: "Speakers",
    rating: 4.4,
    reviews: 654,
    inStock: true,
    discount: 22,
  },
  {
    id: "24",
    name: "Bang & Olufsen Beosound A1",
    price: 249.99,
    description: "Premium materials, clear highs. Luxury portable audio.",
    image: speakerWireless,
    category: "Speakers",
    rating: 4.7,
    reviews: 234,
    inStock: false,
  },

  // Smartwatches
  {
    id: "25",
    name: "Apple Watch Series 9",
    price: 399.99,
    description: "Bright display, health sensors. Most advanced smartwatch.",
    image: smartwatchApple,
    category: "Smartwatches",
    rating: 4.8,
    reviews: 1234,
    inStock: true,
  },
  {
    id: "26",
    name: "Samsung Galaxy Watch 6",
    price: 299.99,
    description: "Wear OS 4, body composition. Android's best watch.",
    image: smartwatchApple,
    category: "Smartwatches",
    rating: 4.7,
    reviews: 876,
    inStock: true,
    discount: 15,
  },
  {
    id: "27",
    name: "Garmin Fenix 7",
    price: 699.99,
    description: "Multi-sport GPS, solar charging. Outdoor adventure companion.",
    image: smartwatchApple,
    category: "Smartwatches",
    rating: 4.9,
    reviews: 543,
    inStock: true,
  },
  {
    id: "28",
    name: "Fitbit Sense 2",
    price: 249.99,
    description: "Stress tracking, ECG app. Health-focused wearable.",
    image: smartwatchApple,
    category: "Smartwatches",
    rating: 4.5,
    reviews: 432,
    inStock: true,
  },
  {
    id: "29",
    name: "Amazfit GTR 4",
    price: 199.99,
    description: "150 sports modes, 14-day battery. Affordable excellence.",
    image: smartwatchApple,
    category: "Smartwatches",
    rating: 4.4,
    reviews: 321,
    inStock: true,
    discount: 20,
  },
  {
    id: "30",
    name: "Withings ScanWatch",
    price: 279.99,
    description: "Medical-grade ECG, analog design. Classic meets smart.",
    image: smartwatchApple,
    category: "Smartwatches",
    rating: 4.6,
    reviews: 289,
    inStock: true,
  },

  // Pendrives
  {
    id: "31",
    name: "SanDisk Ultra 256GB",
    price: 34.99,
    description: "USB 3.0, fast transfers. Reliable storage solution.",
    image: product1,
    category: "Pendrives",
    rating: 4.6,
    reviews: 987,
    inStock: true,
  },
  {
    id: "32",
    name: "Samsung BAR Plus 128GB",
    price: 24.99,
    description: "Metal casing, 300MB/s speed. Durable and fast.",
    image: product1,
    category: "Pendrives",
    rating: 4.5,
    reviews: 654,
    inStock: true,
    discount: 25,
  },
  {
    id: "33",
    name: "Kingston DataTraveler 512GB",
    price: 59.99,
    description: "USB-C compatible, massive storage. Professional grade.",
    image: product1,
    category: "Pendrives",
    rating: 4.7,
    reviews: 432,
    inStock: true,
  },
  {
    id: "34",
    name: "Corsair Flash Voyager 64GB",
    price: 19.99,
    description: "Rugged design, waterproof. Tough as nails.",
    image: product1,
    category: "Pendrives",
    rating: 4.4,
    reviews: 321,
    inStock: true,
  },
  {
    id: "35",
    name: "PNY Turbo 256GB",
    price: 32.99,
    description: "High-speed USB 3.2, budget-friendly. Great value.",
    image: product1,
    category: "Pendrives",
    rating: 4.3,
    reviews: 234,
    inStock: true,
    discount: 18,
  },
  {
    id: "36",
    name: "Lexar JumpDrive 1TB",
    price: 119.99,
    description: "1TB capacity, USB 3.1. Maximum portable storage.",
    image: product1,
    category: "Pendrives",
    rating: 4.8,
    reviews: 543,
    inStock: false,
  },

  // Powerbanks
  {
    id: "37",
    name: "Anker PowerCore 26800",
    price: 69.99,
    description: "Ultra-high capacity, fast charging. Charge multiple devices.",
    image: product2,
    category: "Powerbanks",
    rating: 4.8,
    reviews: 1234,
    inStock: true,
  },
  {
    id: "38",
    name: "RAVPower 20000mAh",
    price: 49.99,
    description: "PD fast charge, dual ports. Compact power solution.",
    image: product2,
    category: "Powerbanks",
    rating: 4.6,
    reviews: 876,
    inStock: true,
    discount: 20,
  },
  {
    id: "39",
    name: "Xiaomi Mi 10000mAh",
    price: 29.99,
    description: "Slim design, two-way charging. Affordable quality.",
    image: product2,
    category: "Powerbanks",
    rating: 4.5,
    reviews: 654,
    inStock: true,
  },
  {
    id: "40",
    name: "Belkin Boost 10K",
    price: 39.99,
    description: "10000mAh, USB-C port. Reliable brand.",
    image: product2,
    category: "Powerbanks",
    rating: 4.4,
    reviews: 432,
    inStock: true,
  },
  {
    id: "41",
    name: "Mophie Powerstation XXL",
    price: 99.99,
    description: "20000mAh, premium build. Apple-certified.",
    image: product2,
    category: "Powerbanks",
    rating: 4.7,
    reviews: 321,
    inStock: true,
  },
  {
    id: "42",
    name: "Aukey 30000mAh Solar",
    price: 79.99,
    description: "Solar charging, rugged. Perfect for camping.",
    image: product2,
    category: "Powerbanks",
    rating: 4.3,
    reviews: 289,
    inStock: true,
    discount: 15,
  },

  // TVs
  {
    id: "43",
    name: "Samsung QN90C 65-inch",
    price: 1999.99,
    description: "Neo QLED, 4K 120Hz. Gaming and movies perfection.",
    image: tvSmart,
    category: "TV",
    rating: 4.9,
    reviews: 543,
    inStock: true,
  },
  {
    id: "44",
    name: "LG C3 OLED 55-inch",
    price: 1499.99,
    description: "Perfect blacks, Dolby Vision. Home theater champion.",
    image: tvSmart,
    category: "TV",
    rating: 4.9,
    reviews: 765,
    inStock: true,
    discount: 12,
  },
  {
    id: "45",
    name: "Sony X90K 75-inch",
    price: 1799.99,
    description: "Full Array LED, Google TV. Big screen excellence.",
    image: tvSmart,
    category: "TV",
    rating: 4.7,
    reviews: 432,
    inStock: true,
  },
  {
    id: "46",
    name: "TCL 6-Series 65-inch",
    price: 899.99,
    description: "Mini-LED, QLED colors. Budget flagship.",
    image: tvSmart,
    category: "TV",
    rating: 4.6,
    reviews: 654,
    inStock: true,
  },
  {
    id: "47",
    name: "Hisense U8K 55-inch",
    price: 799.99,
    description: "ULED, Dolby Atmos. Incredible value.",
    image: tvSmart,
    category: "TV",
    rating: 4.5,
    reviews: 321,
    inStock: true,
    discount: 25,
  },
  {
    id: "48",
    name: "Vizio P-Series 85-inch",
    price: 2499.99,
    description: "Massive screen, 4K HDR. Home cinema scale.",
    image: tvSmart,
    category: "TV",
    rating: 4.4,
    reviews: 289,
    inStock: false,
  },

  // Air Conditioners
  {
    id: "49",
    name: "Daikin 1.5 Ton Inverter",
    price: 649.99,
    description: "Energy efficient, quiet operation. Premium cooling.",
    image: acModern,
    category: "AC",
    rating: 4.8,
    reviews: 432,
    inStock: true,
  },
  {
    id: "50",
    name: "LG Dual Inverter 2 Ton",
    price: 799.99,
    description: "Fast cooling, low power. Smart climate control.",
    image: acModern,
    category: "AC",
    rating: 4.7,
    reviews: 543,
    inStock: true,
  },
  {
    id: "51",
    name: "Samsung WindFree 1 Ton",
    price: 549.99,
    description: "No direct wind, even cooling. Comfortable airflow.",
    image: acModern,
    category: "AC",
    rating: 4.6,
    reviews: 321,
    inStock: true,
    discount: 15,
  },
  {
    id: "52",
    name: "Voltas 1.5 Ton Split",
    price: 449.99,
    description: "Reliable cooling, easy maintenance. Trusted brand.",
    image: acModern,
    category: "AC",
    rating: 4.5,
    reviews: 654,
    inStock: true,
  },
  {
    id: "53",
    name: "Carrier 2 Ton Inverter",
    price: 899.99,
    description: "Heavy-duty cooling, durable. Commercial grade.",
    image: acModern,
    category: "AC",
    rating: 4.7,
    reviews: 289,
    inStock: true,
  },
  {
    id: "54",
    name: "Hitachi 1.2 Ton Window",
    price: 379.99,
    description: "Compact, powerful. Classic window AC.",
    image: acModern,
    category: "AC",
    rating: 4.4,
    reviews: 234,
    inStock: true,
    discount: 20,
  },

  // Refrigerators
  {
    id: "55",
    name: "Samsung 700L French Door",
    price: 1899.99,
    description: "Twin cooling, smart inverter. Family-size freshness.",
    image: product1,
    category: "Refrigerators",
    rating: 4.8,
    reviews: 543,
    inStock: true,
  },
  {
    id: "56",
    name: "LG 600L Side-by-Side",
    price: 1599.99,
    description: "InstaView door, water dispenser. Modern convenience.",
    image: product1,
    category: "Refrigerators",
    rating: 4.7,
    reviews: 432,
    inStock: true,
    discount: 18,
  },
  {
    id: "57",
    name: "Whirlpool 500L Convertible",
    price: 1199.99,
    description: "Flexible storage, adaptive intelligence. Smart fridge.",
    image: product1,
    category: "Refrigerators",
    rating: 4.6,
    reviews: 321,
    inStock: true,
  },
  {
    id: "58",
    name: "Haier 450L Double Door",
    price: 899.99,
    description: "Energy star, frost-free. Efficient cooling.",
    image: product1,
    category: "Refrigerators",
    rating: 4.5,
    reviews: 654,
    inStock: true,
  },
  {
    id: "59",
    name: "Godrej 350L Single Door",
    price: 599.99,
    description: "Compact, reliable. Perfect for small families.",
    image: product1,
    category: "Refrigerators",
    rating: 4.4,
    reviews: 289,
    inStock: true,
    discount: 22,
  },
  {
    id: "60",
    name: "Bosch 800L 4-Door",
    price: 2499.99,
    description: "Premium German engineering. Ultimate food preservation.",
    image: product1,
    category: "Refrigerators",
    rating: 4.9,
    reviews: 234,
    inStock: false,
  },
];
